# src/ApiBundle/Resources/config/doctrine/User.orm.yml
ApiBundle\Entity\AuthCode:
    type:  entity
    table: oauth2_auth_codes
    id:
        id:
            type: integer
            generator:
                strategy: AUTO

    manyToOne:
        client:
          targetEntity: Client
          joinColumn:
              nullable: false
        user:
          targetEntity: User