# src/ApiBundle/Resources/config/doctrine/User.orm.yml
ApiBundle\Entity\Client:
    type:  entity
    table: oauth2_clients
    id:
        id:
            type: integer
            generator:
                strategy: AUTO