# src/ApiBundle/Resources/config/doctrine/User.orm.yml
ApiBundle\Entity\RefreshToken:
    type:  entity
    table: oauth2_refresh_tokens
    id:
        id:
            type: integer
            generator:
                strategy: AUTO

    manyToOne:
        client:
          targetEntity: Client
          joinColumn:
              nullable: false
        user:
          targetEntity: User