api_homepage:
    path:     /
    defaults: { _controller: ApiBundle:Default:index }

api_demos:
    type: rest
    resource: ApiBundle\Controller\DemoController

users:
    resource: "@ApiBundle/Controller/UsersController.php"
    type:     rest

comments:
    type:     rest
    parent:   users
    resource: "@ApiBundle/Controller/CommentsController.php"